Repository CS5500-Team5/Tuiter-React-App, pull requests merged in 2022-04, with the labels that each got.

#3 TUITER-68 Change freeze button text on click
  package-lock.json
  package.json
  src/App.js
  src/components/pollDisplay/index.js
  src/components/profile/index.js
  src/components/profile/login.js
  src/components/profile/signup.js
  src/components/tuits/tuit.js
  src/services/likes-service.js
  src/services/poll-service.js
  src/services/security-service.js
  src/services/tuits-service.js
  src/services/users-service.js
  src/services/vote-service.js
Labels: enhancement

#7 TUITER-59 Test for Frozen Poll
  src/components/tuits/tuit-stats.js
  src/services/tuits-service.js
  src/tests/poll-display.test.js
  src/tests/poll-service.test.js
  src/tests/tuit-list.test.js
  src/tests/tuits-service.test.js
Labels: documentation

#12 Vote test
  package-lock.json
  package.json
  src/services/poll-service.js
  src/services/vote-service.js
  src/tests/vote.test.js
  src/tests/voteUI.test.js
Labels: test

#11 TUITER-83 Delete visible on user and session stores user id
  src/components/pollDisplay/index.js
  src/components/profile/index.js
  src/components/profile/login.js
  src/components/profile/signup.js
  src/components/tuits/tuit.js
Labels: enhancement
